# $NetBSD$

DISTNAME=	unidiff-0.7.5
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_PYPI:=u/unidiff/}

MAINTAINER=	abu.maryam@msafa.org
HOMEPAGE=	http://github.com/matiasb/python-unidiff
COMMENT=	Parse and interact with unified diff data
LICENSE=	mit

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
