BBVERSION=	4.3.0
MAINTAINER=	abu.maryam@msafa.org
HOMEPAGE=	https://buildbot.net/
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
LICENSE=	gnu-gpl-v2

PYTHON_VERSIONS_INCOMPATIBLE=	27

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
