# $NetBSD$

DISTNAME=	croniter-6.0.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	time devel
MASTER_SITES=	${MASTER_SITE_PYPI:=c/croniter/}

MAINTAINER=	abu.maryam@msafa.org
HOMEPAGE=	https://github.com/pallets-eco/croniter
COMMENT=	Iteration for datetime object with cron like format
LICENSE=	mit

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
