# $NetBSD$

DISTNAME=       fitparse-1.2.0
PKGNAME=        ${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=     textproc
MASTER_SITES=   ${MASTER_SITE_PYPI:=f/fitparse/}

MAINTAINER=	root@zta.lk
HOMEPAGE=	https://github.com/dtcooper/python-fitparse
COMMENT=	Python library to parse ANT/Garmin .FIT files.
LICENSE=	mit

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
