# $NetBSD$

DISTNAME=       gpxpy-1.6.2
PKGNAME=        ${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=     textproc
MASTER_SITES=   ${MASTER_SITE_PYPI:=g/gpxpy/}

MAINTAINER=	root@zta.lk
HOMEPAGE=	https://github.com/tkrajina/gpxpy/
COMMENT=	Python library for parsing and manipulating GPX files.
LICENSE=	apache-2.0

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
